### ISSUE TITLE
Change message for unfound id

### ISSUE THREAD

**Issue by PatrickT80** [Squirrel-Network/Knowhere#12]
As in object, i suggest to change the message for unfound id in database.

Actually it return an error message, but to me is more appropriate an information message that stating the searched id isn't blacklisted

**Comment by BluLupo** [comment]
I agree, could you give me an example of a message? @PatrickT80

**Comment by PatrickT80** [comment]
Hi @BluLupo, i think the message can be: Great! Searched id isn't
blacklisted on your network.
